site_name: Roboflow Inference
site_url: https://inference.roboflow.com/
site_author: Roboflow
site_description: Scalable, on-device computer vision deployment.
repo_name: roboflow/inference
repo_url: https://github.com/roboflow/inference
edit_uri: https://github.com/roboflow/inference/tree/main/docs
copyright: Roboflow 2024. All rights reserved.

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/roboflow
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/roboflow
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/roboflow-ai/mycompany/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/roboflow
  analytics:
    provider: google
    property: G-T0CED2YY8K
  version:
    default: 1.0

extra_css:
  - styles.css
  - styles/cookbooks.css

nav:
  - Inference: index.md
  - Learn:
    - Get Started:
      - What is Inference?: quickstart/what_is_inference.md
      - What Devices Can I Use?: quickstart/devices.md
      - Configure an API Key: quickstart/configure_api_key.md
      - Inference 101: quickstart/inference_101.md
    - Using Inference:
      - Native Python API: using_inference/native_python_api.md
      - HTTP API: using_inference/http_api.md
      - Inference Pipeline: using_inference/inference_pipeline.md
    - Documentation:
      - Advanced Usage:
        - Active Learning: enterprise/active-learning/
        - Parallel HTTP API: enterprise/parallel_processing.md
        - Stream Management API: enterprise/stream_management_api.md
      - Inference Helpers:
        - Inference Landing Page: inference_helpers/inference_landing_page.md
        - Inference CLI: inference_helpers/inference_cli.md
        - Inference SDK: inference_helpers/inference_sdk.md
      - Reference:
        - Inference API Reference: docs/reference/
        - HTTP API Reference: api.md
        - Model Aliases: reference_pages/model_aliases.md
        - Model Licensing: quickstart/licensing.md
        - Model Device Compatability: quickstart/compatability_matrix.md
        - Running With Docker: quickstart/docker.md
        - Docker Configuration Options: quickstart/docker_configuration_options.md
        - Contribute to Inference: contributing.md
        - Changelog: https://github.com/roboflow/inference/releases
  - Quickstart Tutorials:
      - Run Your First Model: quickstart/run_a_model.md
      - Run a Fine-Tuned Model: quickstart/explore_models.md
      - Inference Notebook: inference_helpers/inference_landing_page/#inference-notebook
      - Predict on an Image Over HTTP: quickstart/run_model_on_image.md
      - Predict on a Video, Webcam or RTSP Stream: quickstart/run_model_on_rtsp_webcam.md
      - Create a Custom Sink for Inference Pipeline: quickstart/create_a_custom_inference_pipeline_sink.md
      - Predict Over UDP: quickstart/run_model_over_udp.md
      - Collect Data Without a Model: quickstart/stubs.md
  - Models:
    # - Models: models.md
    # - Fine Tuned Models:
    #   - ViT: models/vit.md
    #   - YOLOv5: models/yolov5.md
    #   - YOLOv7: models/yolov7.md
    #   - YOLOv8: models/yolov8.md
    - Foundation Model:
      - What is a Foundation Model?: foundation/about.md
      - CLIP (Classification, Embeddings): foundation/clip.md
      - CogVLM (Multimodal Language Model): foundation/cogvlm.md
      - DocTR (OCR): foundation/doctr.md
      - Grounding DINO (Object Detection): foundation/grounding_dino.md
      - L2CS-Net (Gaze Detection): foundation/gaze.md
      - Segment Anything (Segmentation): foundation/sam.md
      - YOLO-World (Object Detection): foundation/yolo_world.md
      - Grounded SAM(Object Detection/Instance Segmentation): foundation/grounded_sam.md
  - Cookbooks: cookbooks.md

theme:
  name: 'material'
  logo: inference-icon.png
  favicon: inference-icon.png
  custom_dir: docs/theme
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.prune
    - navigation.footer
    - navigation.tracking
    - navigation.indexes
    - navigation.sections
    - content.code.copy

  palette:
  - scheme: default
    primary: 'custom'
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode

  - scheme: slate
    primary: 'custom'
    toggle:
      icon: material/brightness-4
      name: Switch to light mode

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
  - search
  - swagger-ui-tag
  - mkdocs-jupyter
  - social:
      cards_layout_dir: docs/layouts
      cards_layout: custom
  - gen-files:
      scripts:
      - docs/scripts/gen_ref_pages.py
  - literate-nav:
      nav_file: nav.md
  - macros:
      include_dir: docs/include

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

extra_javascript:
  - "https://widget.kapa.ai/kapa-widget.bundle.js"
  - "javascript/init_kapa_widget.js"
  - "javascript/cookbooks.js"
