name: Build and Push Device Manager Container

on:
  release:
    types: [created]

env:
  VERSION: '0.0.0' # Default version, will be overwritten

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: 🛎️ Checkout
        uses: actions/checkout@v3
      -
        name: Read version from file
        run: echo "VERSION=$(DISABLE_VERSION_CHECK=true python ./inference/core/version.py)" >> $GITHUB_ENV
      -
        name: Build and Push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: roboflow/roboflow-device-manager:latest,roboflow/roboflow-device-manager:${{env.VERSION}}
          cache-from: type=registry,ref=roboflow/roboflow-device-manager:cache
          cache-to: type=registry,ref=roboflow/roboflow-device-manager:cache,mode=max
          platforms: linux/amd64,linux/arm64
          file: ./docker/dockerfiles/Dockerfile.device_manager