name: Code Quality & Regression Tests - Jetson 4.6.1

on:
  workflow_dispatch:

jobs:
  build:
    if: ${{ !github.event.act }}
    runs-on: [self-hosted, jetson, jetpack-4.6.1]

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: 🛎️ Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      
      - name: 🦾 Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements/requirements.test.integration.txt
      - name: 🔨 Build and Push Test Docker - Jetson 4.6.1
        run : |
          docker pull roboflow/roboflow-inference-server-jetson-4.6.1:test
          docker build -t roboflow/roboflow-inference-server-jetson-4.6.1:test --cache-from roboflow/roboflow-inference-server-jetson-4.6.1:test -f docker/dockerfiles/Dockerfile.onnx.jetson.4.6.1 .
      - name: 🔋 Start Test Docker - Jetson 4.6.1
        run: |
          PORT=9101 API_KEY=${{ secrets.STAGING_COCO_API_KEY }} INFERENCE_SERVER_REPO=roboflow-inference-server-jetson-4.6.1 make start_test_docker_jetson
      - name: 🧹 Cleanup Test Docker - Jetson 4.6.1
        run: make stop_test_docker
        if: success() || failure()