name: Code Quality & Regression Tests - Device Manager

on:
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to test (e.g. v1.0.0.rc1)'
        required: true

jobs:
  build:
    if: ${{ !github.event.act }}
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: 🛎️ Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event_name == 'workflow_dispatch' && inputs.tag || github.head_ref }}
      
      - name: 🦾 Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements/requirements.test.txt
      - name: 🧹 Lint with flake8
        run: |
          make check_code_quality
      - name: 🧪 Unit Tests for Device Manager
        run: |
          pip install -r requirements/_requirements.txt -r requirements/requirements.device_manager
          python -m pytest tests/device_manager/unit_tests
      - name: 🔨 Build and Push Test Docker
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: roboflow/roboflow-device-manager:test
          cache-from: type=registry,ref=roboflow/roboflow-device-manager:test-cache
          cache-to: type=registry,ref=roboflow/roboflow-device-manager:test-cache,mode=max
          platforms: linux/amd64
          file: ./docker/dockerfiles/Dockerfile.device_manager
      - name: 🔋 Start Test Docker
        run: |
          PORT=9101 INFERENCE_SERVER_REPO=roboflow-inference-server-cpu DOCKERFILE=Dockerfile.device_manager make start_test_docker_cpu
      - name: 🧪 Regression Tests
        run: |
          PORT=9101 API_KEY=${{ secrets.API_KEY }} asl_instance_segmentation_API_KEY=${{ secrets.ASL_INSTANCE_SEGMENTATION_API_KEY }} asl_poly_instance_seg_API_KEY=${{ secrets.ASL_POLY_INSTANCE_SEG_API_KEY }} bccd_favz3_API_KEY=${{ secrets.BCCD_FAVZ3_API_KEY }} bccd_i4nym_API_KEY=${{ secrets.BCCD_I4NYM_API_KEY }} cats_and_dogs_smnpl_API_KEY=${{ secrets.CATS_AND_DOGS_SMNPL_API_KEY }} coins_xaz9i_API_KEY=${{ secrets.COINS_XAZ9I_API_KEY }} melee_API_KEY=${{ secrets.MELEE_API_KEY }} python -m pytest tests/inference/integration_tests
      - name: 🧪 Unit Tests
        run: |
          python -m pip install -r requirements/_requirements.txt -r requirements/requirements.device_manager.txt
          python -m pytest tests/inference_sdk/unit_tests
